### ISSUE TITLE
Leaving the amount field empty seems to break the app

### ISSUE THREAD

**Issue by ghost** [pitonite/exch_cx#3]
![Screenshot_20240705_215808_eXch](https://github.com/pitonite/exch_cx/assets/148219987/5e76e82a-e741-4b27-806d-786a86a46791)

**Comment by pitonite** [comment]
Hi
Can you provide more info ?
The app has not been changed for quite some time, which makes me believe there has been a change on server side

thanks for reporting the issue, I'm investigating this.

**Comment by ghost** [comment]
have no more info to provide, i haven't tested it, it's just my assumption that the cause is an empty amount field

**Comment by pitonite** [comment]
did you import the order or create it on mobile ?

**Comment by ghost** [comment]
created

**Comment by pitonite** [comment]
I have tried creating an order of USDT -> BTC with nothing in amount fields, and it seems to work properly (at least it is working now)

maybe it was a temporary issue ?

**Comment by ghost** [comment]
yeah it worked when i made an order after that, i assume you can tell what happened from the error notification?

**Comment by pitonite** [comment]
the only thing I can tell with that message is that API response was malformed/not what the app expected.
since it got working on its own, I assume either:
- the API was down (under ddos attack for example)
- the API was broken due to some unexpected change (which seems very unlikely)

so overall it seems to be resolved
to allow the app to continue working when the website is under ddos attack, you have to ask for an API key, which you can then use in the app settings. 
you have to contact the website support for getting an API key.
